---
title: "OR-P Networks"
author: "Mustafa Ascha"
date: "November 13, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Background/Intro

Odds ratios are a great way to explain the relationship between two categorical variables, often called the "treatment" and "exposure". Their graphical representation is [often](https://andrewpwheeler.wordpress.com/2013/10/26/odds-ratios-need-to-be-graphed-on-log-scales/) [presented in terms of logistic regression,](http://www.jscarlton.net/post/2015-10-24VisualizingLogistic/) with [categorical line segments](http://www.lexjansen.com/nesug/nesug03/gr/gr007.pdf) across some continuous y-axis.

That's great for logistic regression, but it's limited with respect to the number of associations that can be presented at once. So far in this run of blog posts, we've examined a lot of associations at once, so we'll need a different approach. 

The networks/graphical model approach is well-suited to conveying many odds ratios at once. Moreover, different aesthetics (to use `ggplot2` terminology) can represent relevant statistics such as the p-value. This is what we'll achieve in the present post. 

### Objective

We'll be using [data provided in a previous post]()




### Future directions

* Visualizing these disease networks in d3 or some other interactive medium, such that a large dataset could be visualized and explored